checkout-step: &step checkout

version: 2
jobs:
  tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-repo-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-repo-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - persist_to_workspace:
          root: .
          paths:
            - "node_modules"
      - run: npm test
  build:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: npm run build

workflows:
  version: 2
  one-and-two:
    jobs:
      - job1
      - job2
      - job3:
          requires:
            - job1
          filters:
            branches:
              only:
                - master
      - job3:
          requires:
            - job2
          filters:
            branches:
              only:
                - testcode
      - job4:
          requires:
            - job3
          filters:
            branches:
              only:
                - testcode
      - job4:
          requires:
            - job3
          filters:
            branches:
              only:
                - master
      - job5:
          requires:
            - job4
          filters:
            branches:
              only:
                - master
                - release
