checkout-step: &step checkout

version: 2
jobs:
  job1:
    docker:
      - image: circleci/node:10
    step:
      - *step
      - run: npm install
      - run: npm test
  job2:
    docker:
      - image: circleci/node:10
    step:
      - *step
      - run: cat README.md

workflows:
  version: 2
  one-and-two:
    jobs:
      - job1
      - job2:
          requires:
            - job1

